site_name: GOS
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.sections
markdown_extensions:
   - admonition
   - pymdownx.tabbed
   - pymdownx.superfences
repo_url: https://github.com/roger21gm/GOS
repo_name: roger21gm/GOS
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roger21gm
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/roger21gm
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rogergeneroso

nav:
   - Getting Started:
      - Introduction: 'README.md'
      - GOS & BUP:
         - GOS: 'gos_result.md'
         - BUP: 'bup_result.md'
      - Quick start: 'quickstart.md'
   - Language Specification:
      - Introduction: bup_intro.md
      - Blocks: bup.md
      - Data types: data.md
      - Identifiers: identifiers.md
      - Comments: comments.md
      - Expressions: expr.md
      - Data access: access.md
      - Lists: lists.md
      - Constraints: constraints.md
      - Strings: strings.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
